apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: abhishekporwal836/flask-app-buyogo:latest
          resources: #added for resource management
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: "mongodb+srv://abhishekporwal836:<password>@flask-app-buyogo.5yoi7.mongodb.net/?retryWrites=true&w=majority&appName=flask-app-BUYOGO"

